import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-black-100 p-10">
          <h1 className="text-xl font-bold text-black text-center dark:invert font-calibri">My App Header</h1>
        </header>
        <main className ="p-4">{children}</main>
        <footer className="bg-gray-800 text-white text-center p-2 font-calibri">
          &copy; Taeseok Lee
        </footer>
      </body>
    </html>
  );
}
